# Generated by Django 3.0.8 on 2020-07-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200726_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.CharField(choices=[('18 - 25', '18 - 25'), ('25 - 30', '25 - 30'), ('30 - 35', '30 - 35'), ('35 - 45', '35 - 45'), ('45 - 55', '45 - 55'), ('55 or older', '55 or older')], default=False, max_length=100),
        ),
    ]
