# Generated by Django 3.0.8 on 2020-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200726_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='Borrower_Status',
            field=models.CharField(choices=[('Auto Loan', 'Auto Loan'), ('Business Loan', 'Business Loan'), ('Credit Cards', 'Credit Cards'), ('Home Mortgage', 'Home Mortgage'), ('Student Loan', 'Student Loan'), ('Personal Loan', 'Personal Loan')], default=False, max_length=100),
        ),
    ]
