# Generated by Django 3.0.8 on 2020-07-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_survey_kids'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='SurveyForm',
        ),
    ]
