# Generated by Django 3.0.8 on 2020-07-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20200726_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='borrower_status',
        ),
    ]
