# Generated by Django 3.0.8 on 2020-07-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_remove_survey_borrower_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='age',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='gender',
        ),
    ]
