# Generated by Django 3.0.8 on 2020-07-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20200726_1216'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table=None,
        ),
    ]
