# Generated by Django 3.0.8 on 2020-07-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20200726_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='Profile_Name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='age',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='gender',
        ),
    ]
