# Generated by Django 3.0.8 on 2020-07-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20200727_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='borrower_status',
            field=models.CharField(choices=[('Auto Loan', 'Auto Loan'), ('Business Loan', 'Business Loan'), ('Credit Cards', 'Credit Cards'), ('Home Mortgage', 'Home Mortgage'), ('Student Loan', 'Student Loan'), ('Personal Loan', 'Personal Loan')], default=False, max_length=100),
        ),
    ]
