# Generated by Django 3.0.8 on 2020-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20200727_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='Kids',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='Pet',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='Profile_Name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='Purchases',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='Smoker',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='age',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='current_residence',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='daily_internet_usage',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='education',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='employment_industry',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='employment_status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='exercise',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='gender',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='household_income',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='marital_status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='news_sources',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='own',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='political_affiliation',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='social_media',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='travel_frequency',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='borrower_status',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
