# Generated by Django 3.0.8 on 2020-07-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20200727_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Kids',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
