# Generated by Django 3.0.8 on 2020-07-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_auto_20200727_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Kids',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
