# Generated by Django 3.0.8 on 2020-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_remove_survey_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='Kids',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
