# Generated by Django 3.0.8 on 2020-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_survey_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
