# Generated by Django 3.0.8 on 2020-07-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_auto_20200727_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
