# Generated by Django 3.0.8 on 2020-07-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_auto_20200727_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='own',
            new_name='car',
        ),
    ]
