# Generated by Django 3.0.8 on 2020-07-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_auto_20200727_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey',
            new_name='Surveys',
        ),
    ]
