# Generated by Django 3.0.8 on 2020-07-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_auto_20200728_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='Kids',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Pet',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Purchases',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Smoker',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='car',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='daily_internet_usage',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='education',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='employment_industry',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='household_income',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='news_sources',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='political_affiliation',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='travel_frequency',
        ),
    ]
