# Generated by Django 3.0.8 on 2020-07-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_auto_20200728_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='education',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
