# Generated by Django 3.0.8 on 2020-07-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_survey_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='education',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
