# Generated by Django 3.0.8 on 2020-07-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0042_auto_20200728_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='education',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
