# Generated by Django 3.0.8 on 2020-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_auto_20200728_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Name', models.CharField(max_length=100, unique=True)),
                ('borrower_status', models.CharField(default=False, max_length=100)),
                ('gender', models.CharField(default=None, max_length=100)),
                ('age', models.CharField(default=None, max_length=100)),
                ('current_residence', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('education', models.CharField(blank=True, default=False, max_length=100, null=True)),
            ],
        ),
    ]
