# Generated by Django 3.0.8 on 2020-07-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_survey1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='current_residence',
        ),
    ]
