# Generated by Django 3.0.8 on 2020-07-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_auto_20200728_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='Profile_Name',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
