# Generated by Django 3.0.8 on 2020-07-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_auto_20200728_0720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey1',
        ),
    ]
